### ISSUE TITLE
Dev avis et commentaires

### ISSUE THREAD

**Issue by lauriane-f** [betagouv/ellesfontlaphoto#210]
les maquettes sont terminées par ici : https://www.figma.com/file/KKzsnDnoraBbkuXfgyPZQ1/Elles-font-la-culture?node-id=727%3A16943 @nadiaauger

**Comment by lauriane-f** [comment]
NOTATION 
- donner la possibilité de supprimer son vote avant validation en recliquant dessus
- mettre à jour les résultats ou refresh la page quand on clique sur valider ?

COMMENTAIRE - rien à dire, c'est parf !

cc @nadiaauger

**Comment by wittsarah** [comment]
C'est top, bravo @nadiaauger ! 

Je sais pas si c'est vraiment utile mais limiter à un nombre maximum de caractères les commentaires pour éviter d'avoir des textes à rallonge sur la page ?
