### ISSUE TITLE
Rendre le montant de l'aide obligatoire

### ISSUE THREAD

**Issue by wittsarah** [betagouv/ellesfontlaphoto#251]
Hello @nadiaauger 

Dans la mise en ligne d'aides, possible de rendre la section **Montant de l'aide** comme un champs obligatoire ? 
Sinon le champs apparait vide, c'est bizarre. Et nous allons faire remplir des aides par une personne du dpt photos, comme ça elle sera obligée de le renseigner :)

Merci !

**Comment by lauriane-f** [comment]
point intégré dans une autre issue @wittsarah, merci !
